---
  ## This playbook will query config in text format
  ## and store it

- name: Backup config
  hosts: all
  connection: local
  gather_facts: no
  vars_files: 
    - ../external_vars.yml

  tasks:

  - name: Get config in TEXT format
    junos_facts:
      config: yes
      config_format: text
      provider: "{{ credentials }}" 
    register: result_text

  - name: Save config (TEXT format)  in configs/
    copy: 
      content="{{ result_text.ansible_facts.config }}" 
      dest=../configs/{{ course_name }}/{{ section_name }}/{{ inventory_hostname }}.{{ filename_modifier | default('') }}.conf
