---
  ## This playbook will query config in text format
  ## and store it

- name: Backup config
  hosts: all
  connection: local
  gather_facts: no
  vars_files: 
    - ../external_vars.yml

  tasks:
  - name: Get config in TEXT format
    junos_facts:
      gather_subset: config
      config_format: text
      provider: "{{ credentials }}"
    register: result

#  - debug:
#      var: result.ansible_facts.ansible_net_config

  - name: Save config (TEXT format)  in configs/
    copy: 
      content="{{ result.ansible_facts.ansible_net_config }}" 
      dest="../configs/{{ course_name }}/{{ section_name }}/{{ inventory_hostname }}.{{ filename_modifier | default('') }}.conf"
